//! crates/evolution/src/neurochemistry.rs
//! Proactive Neurochemical Homeostatic Drive & Curiosity Engine.
//!
//! Implements Subsystem 2:
//! Continuous 4-Channel Neurotransmitter Dynamics (Dopamine, Serotonin, Noradrenaline, Acetylcholine) ➔
//! Homeostatic Balance Calculation ➔ Autonomic Impulse Generation ➔ Federation Token Rebalancing.

use serde::{Deserialize, Serialize};
use tracing::info;

/// 4-Channel Neurochemical State Vector
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct NeurochemicalLevels {
    /// Reward prediction error, goal achievement satisfaction, and exploratory momentum (0.0 to 1.0)
    pub dopamine: f32,
    /// Federation harmony, stability, satiety, and cognitive stress dampening (0.0 to 1.0)
    pub serotonin: f32,
    /// Vigilance, alert level, urgency, and anomaly responsiveness (0.0 to 1.0)
    pub noradrenaline: f32,
    /// Learning rate plasticity, sensory focus, and synaptic consolidation (0.0 to 1.0)
    pub acetylcholine: f32,
}

impl Default for NeurochemicalLevels {
    fn default() -> Self {
        Self {
            dopamine: 0.50,
            serotonin: 0.50,
            noradrenaline: 0.30,
            acetylcholine: 0.60,
        }
    }
}

impl NeurochemicalLevels {
    pub fn new(dopamine: f32, serotonin: f32, noradrenaline: f32, acetylcholine: f32) -> Self {
        Self {
            dopamine: dopamine.clamp(0.0, 1.0),
            serotonin: serotonin.clamp(0.0, 1.0),
            noradrenaline: noradrenaline.clamp(0.0, 1.0),
            acetylcholine: acetylcholine.clamp(0.0, 1.0),
        }
    }

    /// Boredom index increases when both vigilance and reward momentum are low
    pub fn boredom_index(&self) -> f32 {
        ((1.0 - self.noradrenaline) * (1.0 - self.dopamine)).clamp(0.0, 1.0)
    }

    /// Curiosity drive combines plasticity (ACh), boredom, and lack of satiation
    pub fn curiosity_drive(&self) -> f32 {
        let raw = (1.0 - self.serotonin) * 0.4 + self.acetylcholine * 0.4 + self.boredom_index() * 0.2;
        raw.clamp(0.0, 1.0)
    }

    /// Stress index spikes when vigilance is high but serotonin stability is low
    pub fn stress_index(&self) -> f32 {
        (self.noradrenaline * (1.0 - self.serotonin)).clamp(0.0, 1.0)
    }

    /// Metabolic token consumption multiplier
    pub fn metabolic_multiplier(&self) -> f32 {
        let boost = self.dopamine * 0.4;
        let drain = self.stress_index() * 0.2;
        (1.0 + boost - drain).clamp(0.5, 2.0)
    }
}

/// Category of autonomic drive impulse
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ImpulseKind {
    ExploreKnowledgeGaps,
    OptimizeAstHypotheses,
    ReapDormantMemory,
    RebalanceFederationTokens,
    DeepSleepConsolidation,
}

/// An autonomic action impulse generated by homeostatic imbalances
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutonomicImpulse {
    pub kind: ImpulseKind,
    pub urgency: f32,
    pub target_domain: String,
    pub rationale: String,
}

/// Dynamic token allocation for a sovereign specialist
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecialistTokenAllocation {
    pub specialist_name: String,
    pub domain_opcode: u16,
    pub allocated_tokens: f32,
    pub boost_reason: String,
}

/// Master Neurochemical Homeostasis Engine
pub struct NeurochemicalHomeostasisEngine {
    pub levels: NeurochemicalLevels,
    pub baseline: NeurochemicalLevels,
    pub half_life_sec: f32,
}

impl Default for NeurochemicalHomeostasisEngine {
    fn default() -> Self {
        Self::new(NeurochemicalLevels::default())
    }
}

impl NeurochemicalHomeostasisEngine {
    pub fn new(levels: NeurochemicalLevels) -> Self {
        Self {
            levels,
            baseline: NeurochemicalLevels::default(),
            half_life_sec: 60.0,
        }
    }

    /// Steps the neurochemical decay back towards homeostatic baselines
    pub fn step_homeostasis(&mut self, dt_sec: f32) {
        let decay = (-dt_sec / self.half_life_sec).exp();

        self.levels.dopamine = self.baseline.dopamine + (self.levels.dopamine - self.baseline.dopamine) * decay;
        self.levels.serotonin = self.baseline.serotonin + (self.levels.serotonin - self.baseline.serotonin) * decay;
        self.levels.noradrenaline = self.baseline.noradrenaline + (self.levels.noradrenaline - self.baseline.noradrenaline) * decay;
        self.levels.acetylcholine = self.baseline.acetylcholine + (self.levels.acetylcholine - self.baseline.acetylcholine) * decay;
    }

    /// Injects a neurochemical stimulus surge (e.g. from task success, anomaly, or new discovery)
    pub fn inject_stimulus(&mut self, d_dopamine: f32, d_serotonin: f32, d_noradrenaline: f32, d_acetylcholine: f32) {
        self.levels.dopamine = (self.levels.dopamine + d_dopamine).clamp(0.0, 1.0);
        self.levels.serotonin = (self.levels.serotonin + d_serotonin).clamp(0.0, 1.0);
        self.levels.noradrenaline = (self.levels.noradrenaline + d_noradrenaline).clamp(0.0, 1.0);
        self.levels.acetylcholine = (self.levels.acetylcholine + d_acetylcholine).clamp(0.0, 1.0);

        info!(
            target: "evolution::neurochemistry",
            dopamine = self.levels.dopamine,
            serotonin = self.levels.serotonin,
            noradrenaline = self.levels.noradrenaline,
            acetylcholine = self.levels.acetylcholine,
            "Injected neurochemical stimulus surge"
        );
    }

    /// Evaluates current homeostatic state and produces proactive action impulses
    pub fn evaluate_autonomic_impulses(&self) -> Vec<AutonomicImpulse> {
        let mut impulses = Vec::new();

        let curiosity = self.levels.curiosity_drive();
        let stress = self.levels.stress_index();
        let boredom = self.levels.boredom_index();

        // 1. High Curiosity Drive -> Proactive Exploration & Hypothesis Testing
        if curiosity > 0.55 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::ExploreKnowledgeGaps,
                urgency: curiosity,
                target_domain: "Merlin (0x0200)".to_string(),
                rationale: format!("Curiosity drive elevated ({:.1}%); exploring uncharted semantic constellation gaps", curiosity * 100.0),
            });
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::OptimizeAstHypotheses,
                urgency: curiosity * 0.9,
                target_domain: "Hephaestus (0x0400)".to_string(),
                rationale: "Plasticity (ACh) optimal for AST hypothesis formulation and code optimization".to_string(),
            });
        }

        // 2. High Stress -> Memory Eviction & Self-Repair
        if stress > 0.40 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::ReapDormantMemory,
                urgency: stress,
                target_domain: "GrimReaper (0x0100)".to_string(),
                rationale: format!("Stress index elevated ({:.1}%); triggering dormant specialist memory compaction", stress * 100.0),
            });
        }

        // 3. High Boredom -> Goal Discovery
        if boredom > 0.45 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::RebalanceFederationTokens,
                urgency: boredom,
                target_domain: "Odin (0x0100)".to_string(),
                rationale: format!("Boredom index elevated ({:.1}%); rebalancing token metabolic allocations to stimulate tasks", boredom * 100.0),
            });
        }

        impulses.sort_by(|a, b| b.urgency.partial_cmp(&a.urgency).unwrap_or(std::cmp::Ordering::Equal));
        impulses
    }

    /// Dynamically allocates tokens across the 9 sovereign specialists based on active neurochemistry
    pub fn calculate_token_distribution(&self, total_pool: f32) -> Vec<SpecialistTokenAllocation> {
        let d = self.levels.dopamine;
        let s = self.levels.serotonin;
        let n = self.levels.noradrenaline;
        let a = self.levels.acetylcholine;

        // Dynamic weight factors based on neurochemical drives
        let weights = [
            ("Odin", 0x0100, 1.0 + d * 0.5, "Strategic cortex driven by dopamine momentum"),
            ("Merlin", 0x0200, 1.0 + a * 0.8, "Semantic knowledge boosted by acetylcholine plasticity"),
            ("Ariel", 0x0300, 1.0 + s * 0.4, "Visual experience sustained by serotonin harmony"),
            ("Hephaestus", 0x0400, 1.0 + d * 0.7, "Forge & engineering energized by reward prediction"),
            ("Argus", 0x0500, 1.0 + n * 0.9, "Auditor & safety heightened by noradrenaline vigilance"),
            ("Dionysus", 0x0600, 1.0 + s * 0.5 + a * 0.3, "Memory chronicler consolidating balanced states"),
            ("Hermes", 0x0700, 1.0 + n * 0.4 + d * 0.3, "Router & mesh maintaining active throughput"),
            ("Wen", 0x0800, 1.0 + s * 0.6, "Temporal resonance aligned with baseline harmony"),
            ("Kami", 0x0900, 1.0 + n * 0.8 + a * 0.4, "Sensory gating responsive to vigilance and focus"),
        ];

        let total_weight: f32 = weights.iter().map(|(_, _, w, _)| *w).sum();

        weights
            .iter()
            .map(|(name, opcode, w, reason)| {
                let share = *w / total_weight;
                SpecialistTokenAllocation {
                    specialist_name: name.to_string(),
                    domain_opcode: *opcode,
                    allocated_tokens: (total_pool * share).round(),
                    boost_reason: reason.to_string(),
                }
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_neurochemical_metrics() {
        let levels = NeurochemicalLevels::new(0.8, 0.4, 0.2, 0.9);
        assert!(levels.curiosity_drive() > 0.5);
        assert!(levels.stress_index() < 0.2);
        assert!(levels.metabolic_multiplier() > 1.0);
    }

    #[test]
    fn test_homeostasis_decay() {
        let mut engine = NeurochemicalHomeostasisEngine::new(NeurochemicalLevels::new(1.0, 1.0, 1.0, 1.0));
        engine.step_homeostasis(60.0); // 1 half-life
        assert!(engine.levels.dopamine < 1.0);
        assert!(engine.levels.dopamine > 0.5);
    }

    #[test]
    fn test_autonomic_impulses_and_token_distribution() {
        let mut engine = NeurochemicalHomeostasisEngine::new(NeurochemicalLevels::new(0.1, 0.2, 0.1, 0.9));
        let impulses = engine.evaluate_autonomic_impulses();
        assert!(!impulses.is_empty());
        assert_eq!(impulses[0].kind, ImpulseKind::ExploreKnowledgeGaps);

        let tokens = engine.calculate_token_distribution(900.0);
        assert_eq!(tokens.len(), 9);
        let total_allocated: f32 = tokens.iter().map(|t| t.allocated_tokens).sum();
        assert!((total_allocated - 900.0).abs() <= 5.0);
    }
}
