[workspace]
members = [
    "core/hypervisor",
    "core/nervous_system",
    "sdk/rust",
    "components/intelligence",
    "components/storage",
    "components/sabs",
    "components/skills",
    "components/genetics",
    "components/digestion",
    "components/biology",
    "components/agents",
    "components/constellation",
    "components/control",
    "components/hive",
    "components/compute",
    "components/scientific_analyzer",
    "components/paths",
]
exclude = [
    "extensions/wasm/test_enzyme"
]
resolver = "2"
