[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
regex = "1.10"
ast_auditor = { path = "../crates/ast_auditor" }
serde_json = "1.0"
walkdir = "2.5"

[dev-dependencies]
tempfile = { workspace = true }

