#![allow(unused)]
#![recursion_limit = "256"]

pub mod adaptive_learning_rate;
pub mod batch_processor;
pub mod capability_registry;
pub mod cellular_automata;
pub mod chaos_monkey;
pub mod compaction_engine;
pub mod compression;
pub mod concept_drift;
pub mod config;
pub mod config_validation;
pub mod consensus_engine;
pub mod dashboard;
pub mod distributed_checkpoint;
pub mod error;
pub mod event_log;
pub mod execution;
pub mod fluid_routing;
#[cfg(test)]
mod graceful_degradation_tests;
pub mod hardened_env;
pub mod hardware_layer;
pub mod hid_driver;
pub mod input_validation;
pub mod inter_agent;
pub mod logging;
pub mod mcp_bridge;
pub mod metadata_ingestor;
pub mod metrics_aggregator;
pub mod micro_vm;
pub mod native_ingestion;
pub mod nats_client;
pub mod nlm_sentinel;
pub mod performance_benchmark;
pub mod persistence;
pub mod predictive_load_balancer;
pub mod predictive_models;
pub mod profile_compiler;
pub mod profile_merger;
pub mod profile_registry;
pub mod profile_schema;
pub mod quantum_surface;
pub mod rate_limit;
pub mod reasoning;
pub mod registry;
#[cfg(test)]
mod rkyv_test;
pub mod relativity_engine;
pub mod resilience;
pub mod runtime_governor;
pub mod sandboxed_network;
pub mod screen_capture;
pub mod security_hardener;
pub mod semantic_indexing;
pub mod signal_bridge;
pub mod spatial_delta_gate;
pub mod spatial_kinetic_engine;
pub mod specialist_memory;
pub mod spectral_layout;
pub mod state;
pub mod state_replicator;
pub mod state_snapshot;
pub mod stress_tester;
pub mod substrate;
pub mod symbolic_math;
pub mod system_integrity;
pub mod system_metrics;
pub mod task_analysis;
pub mod task_worker;
pub mod tensor_router;
pub mod trait_loader;
pub mod ui_broker;
pub mod unified_registry;
pub mod util;
pub mod visual_perception;
pub mod wgpu_reflex_pipeline;
pub mod win32_intercept;
pub mod worker_runner;
pub mod workspace;
pub use crate::capability_registry as node_registry;
pub use crate::capability_registry as chromosome_registry;
pub use crate::profile_compiler as genome_compiler;
pub use crate::profile_merger as genetic_recombination;
pub use crate::profile_registry as hox_registry;
pub use crate::profile_schema as hox_map_schema;
pub use crate::screen_capture as retina_module;
pub use crate::worker_runner as enzyme_runner;
