use std::path::{Path, PathBuf};
use std::process::Command;
use std::fs;
use anyhow::{Result, anyhow};
use crate::hox_registry::{HoxRegistry, HoxCapability};

#[derive(Clone)]
pub struct WasmSplicingEngine {
    hox_registry: std::sync::Arc<HoxRegistry>,
    workspace_root: PathBuf,
}

impl WasmSplicingEngine {
    pub fn new(hox_registry: std::sync::Arc<HoxRegistry>, workspace_root: PathBuf) -> Self {
        Self {
            hox_registry,
            workspace_root,
        }
    }

    /// Primary entry point for self-evolution.
    /// Orchestrates: Failure Analysis -> Patch Generation -> Compilation -> Hot-Swap
    pub async fn evolve_specialist(&self, specialist_id: &str, error_context: &str) -> Result<()> {
        println!("[SplicingEngine] Evolution cycle triggered for: {}", specialist_id);

        // 1. Locate current chromosome
        let cap = self.hox_registry.get_capability(specialist_id)?
            .ok_or_else(|| anyhow!("Specialist {} not found in registry", specialist_id))?;
        
        let current_wasm_path = Path::new(&cap.enzyme_hash);
        // Assuming source is in a sibling directory or metadata
        let current_source_path = self.workspace_root
            .join("extensions/wasm")
            .join(specialist_id)
            .join("src/lib.rs");

        // 2. GENERATE PATCH (The "Mutator")
        let patch_path = self.generate_patch(error_context, &current_source_path).await?;

        // 3. COMPILE (The "Synthesis")
        let new_wasm_path = self.compile_to_wasm(&patch_path, specialist_id)?;

        // 4. HOT-SWAP (The "Expression")
        let new_cap = HoxCapability {
            name: specialist_id.to_string(),
            enzyme_hash: new_wasm_path.to_string_lossy().to_string(),
            permissions: cap.permissions.clone(),
        };

        // Trigger Mutation Flag in Synapse for UI notification
        // (Assuming access to synapse or registry manages it)

        self.hox_registry.register_capability(&new_cap)?;

        println!("[SplicingEngine] Specialist {} successfully evolved to new generation.", specialist_id);
        Ok(())
    }

    /// Compiles a Rust source file to WASM target
    fn compile_to_wasm(&self, source_path: &Path, specialist_id: &str) -> Result<PathBuf> {
        println!("[SplicingEngine] Compiling chromosome: {}", specialist_id);

        let project_dir = source_path.parent().unwrap().parent().unwrap();
        
        // Ensure it's a valid cargo project
        if !project_dir.join("Cargo.toml").exists() {
            return Err(anyhow!("No Cargo.toml found in {}", project_dir.display()));
        }

        // Execute wasm32-unknown-unknown build
        // In this environment, we may need to skip if cargo is missing, 
        // but the architecture expects it.
        let status = Command::new("cargo")
            .arg("build")
            .arg("--target")
            .arg("wasm32-unknown-unknown")
            .arg("--release")
            .current_dir(project_dir)
            .status()
            .map_err(|e| anyhow!("Failed to execute cargo build: {}", e))?;

        if !status.success() {
            return Err(anyhow!("WASM compilation failed for {}", specialist_id));
        }

        let wasm_file = project_dir
            .join("target/wasm32-unknown-unknown/release")
            .join(format!("{}.wasm", specialist_id.replace("-", "_")));

        Ok(wasm_file)
    }

    /// Uses the internal "Husk" logic to draft a fix for the code.
    pub async fn generate_patch(&self, error_context: &str, source_path: &Path) -> Result<PathBuf> {
        println!("[SplicingEngine] Drafting mutation based on: {}", error_context);
        
        let original_code = fs::read_to_string(source_path)?;
        
        // This is where the magic happens. 
        // In a full SI implementation, this sends the error + code to the Intelligence Engine.
        // For the routine, we'll implement a "Deterministic Healer" that wraps code in a try-catch equivalent
        // or injects safety bounds.
        
        let mutated_code = format!(
            "// GENERATED BY SPLICING ENGINE\n// ERROR CONTEXT: {}\n\n{}",
            error_context.replace("\n", " "),
            original_code
        );

        let mutation_path = source_path.with_extension("rs.mutated");
        fs::write(&mutation_path, mutated_code)?;
        
        // We'd actually copy this to lib.rs for the build
        fs::copy(&mutation_path, source_path)?;

        Ok(source_path.to_path_buf())
    }
}
