[package]\nname = " outer_loop\\nversion = \0.1.0\\nedition = \2021\\n\n[dependencies]\nanyhow = \1.0\\nthiserror = \2.0\\ntokio = { version = \1.0\, features = [\full\] }\ninner_loop = { path = ../inner_loop }\nverification = { path = ../verification }\nhotload = { path = ../hotload }\nstate_serialization = { path = ../state_serialization }\nserde = { version = \1.0\, features = [\derive\] }
