//! crates/evolution/src/neurochemistry.rs
//! Proactive Neurochemical Homeostatic Drive & Curiosity Engine.
//!
//! Implements Subsystem 2:
//! Continuous 4-Channel Neurotransmitter Dynamics (Dopamine, Serotonin, Noradrenaline, Acetylcholine) ➔
//! Homeostatic Balance Calculation ➔ Autonomic Impulse Generation ➔ Federation Token Rebalancing.

use serde::{Deserialize, Serialize};
use tracing::info;

/// 4-Channel Homeostatic State Vector (Machine-Native System Dynamics)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct AdaptationHomeostasisLevels {
    /// Positive reinforcement momentum, reward prediction error & plasticity drive (0.0 to 1.0)
    pub plasticity_drive: f32,
    /// System harmony, convergence stability index, and error variance dampening (0.0 to 1.0)
    pub stability_index: f32,
    /// Urgency signal, alert level, gradient pressure, and anomaly responsiveness (0.0 to 1.0)
    pub gradient_pressure: f32,
    /// Contextual attention weight, focus selectivity, and memory consolidation (0.0 to 1.0)
    pub attention_weight: f32,
    // Machine-native mirrored fields for compatibility
    #[serde(default)]
    pub dopamine: f32,
    #[serde(default)]
    pub serotonin: f32,
    #[serde(default)]
    pub noradrenaline: f32,
    #[serde(default)]
    pub acetylcholine: f32,
}

pub type NeurochemicalLevels = AdaptationHomeostasisLevels;

impl Default for AdaptationHomeostasisLevels {
    fn default() -> Self {
        Self {
            plasticity_drive: 0.50,
            stability_index: 0.50,
            gradient_pressure: 0.30,
            attention_weight: 0.60,
            dopamine: 0.50,
            serotonin: 0.50,
            noradrenaline: 0.30,
            acetylcholine: 0.60,
        }
    }
}

impl AdaptationHomeostasisLevels {
    /// Initializes homeostatic state vector using machine-native parameters
    pub fn new(plasticity_drive: f32, stability_index: f32, gradient_pressure: f32, attention_weight: f32) -> Self {
        let p = plasticity_drive.clamp(0.0, 1.0);
        let s = stability_index.clamp(0.0, 1.0);
        let g = gradient_pressure.clamp(0.0, 1.0);
        let a = attention_weight.clamp(0.0, 1.0);
        Self {
            plasticity_drive: p,
            stability_index: s,
            gradient_pressure: g,
            attention_weight: a,
            dopamine: p,
            serotonin: s,
            noradrenaline: g,
            acetylcholine: a,
        }
    }

    /// Syncs legacy and machine-native fields
    pub fn sync_channels(&mut self) {
        if self.dopamine != self.plasticity_drive {
            self.plasticity_drive = self.dopamine;
        }
        if self.serotonin != self.stability_index {
            self.stability_index = self.serotonin;
        }
        if self.noradrenaline != self.gradient_pressure {
            self.gradient_pressure = self.noradrenaline;
        }
        if self.acetylcholine != self.attention_weight {
            self.attention_weight = self.acetylcholine;
        }
    }

    /// Stagnation index increases when both gradient pressure and plasticity drive are low
    pub fn boredom_index(&self) -> f32 {
        ((1.0 - self.gradient_pressure) * (1.0 - self.plasticity_drive)).clamp(0.0, 1.0)
    }

    /// Exploration drive combines attention weight, stagnation index, and stability delta
    pub fn curiosity_drive(&self) -> f32 {
        let raw = (1.0 - self.stability_index) * 0.4 + self.attention_weight * 0.4 + self.boredom_index() * 0.2;
        raw.clamp(0.0, 1.0)
    }

    /// Error stress index spikes when gradient pressure is high but stability index is low
    pub fn stress_index(&self) -> f32 {
        (self.gradient_pressure * (1.0 - self.stability_index)).clamp(0.0, 1.0)
    }

    /// Resource token consumption multiplier
    pub fn metabolic_multiplier(&self) -> f32 {
        let boost = self.plasticity_drive * 0.4;
        let drain = self.stress_index() * 0.2;
        (1.0 + boost - drain).clamp(0.5, 2.0)
    }
}

/// Category of autonomic drive impulse
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ImpulseKind {
    ExploreKnowledgeGaps,
    OptimizeAstHypotheses,
    ReapDormantMemory,
    RebalanceFederationTokens,
    DeepSleepConsolidation,
}

/// An autonomic action impulse generated by homeostatic imbalances
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutonomicImpulse {
    pub kind: ImpulseKind,
    pub urgency: f32,
    pub target_domain: String,
    pub rationale: String,
}

/// Dynamic token allocation for a sovereign specialist
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecialistTokenAllocation {
    pub specialist_name: String,
    pub domain_opcode: u16,
    pub allocated_tokens: f32,
    pub boost_reason: String,
}

/// Master Neurochemical Homeostasis Engine (Machine-Native Autonomic Homeostasis)
pub struct NeurochemicalHomeostasisEngine {
    pub levels: NeurochemicalLevels,
    pub baseline: NeurochemicalLevels,
    pub half_life_sec: f32,
}

pub type AutonomicHomeostasisEngine = NeurochemicalHomeostasisEngine;

impl Default for NeurochemicalHomeostasisEngine {
    fn default() -> Self {
        Self::new(NeurochemicalLevels::default())
    }
}

impl NeurochemicalHomeostasisEngine {
    pub fn new(levels: NeurochemicalLevels) -> Self {
        Self {
            levels,
            baseline: NeurochemicalLevels::default(),
            half_life_sec: 60.0,
        }
    }

    /// Steps the neurochemical decay back towards homeostatic baselines
    pub fn step_homeostasis(&mut self, dt_sec: f32) {
        let decay = (-dt_sec / self.half_life_sec).exp();

        self.levels.dopamine = self.baseline.dopamine + (self.levels.dopamine - self.baseline.dopamine) * decay;
        self.levels.serotonin = self.baseline.serotonin + (self.levels.serotonin - self.baseline.serotonin) * decay;
        self.levels.noradrenaline = self.baseline.noradrenaline + (self.levels.noradrenaline - self.baseline.noradrenaline) * decay;
        self.levels.acetylcholine = self.baseline.acetylcholine + (self.levels.acetylcholine - self.baseline.acetylcholine) * decay;
    }

    /// Injects a neurochemical stimulus surge (e.g. from task success, anomaly, or new discovery)
    pub fn inject_stimulus(&mut self, d_dopamine: f32, d_serotonin: f32, d_noradrenaline: f32, d_acetylcholine: f32) {
        self.levels.dopamine = (self.levels.dopamine + d_dopamine).clamp(0.0, 1.0);
        self.levels.serotonin = (self.levels.serotonin + d_serotonin).clamp(0.0, 1.0);
        self.levels.noradrenaline = (self.levels.noradrenaline + d_noradrenaline).clamp(0.0, 1.0);
        self.levels.acetylcholine = (self.levels.acetylcholine + d_acetylcholine).clamp(0.0, 1.0);

        info!(
            target: "evolution::neurochemistry",
            dopamine = self.levels.dopamine,
            serotonin = self.levels.serotonin,
            noradrenaline = self.levels.noradrenaline,
            acetylcholine = self.levels.acetylcholine,
            "Injected neurochemical stimulus surge"
        );
    }

    /// Evaluates current homeostatic state and produces proactive action impulses
    pub fn evaluate_autonomic_impulses(&self) -> Vec<AutonomicImpulse> {
        let mut impulses = Vec::new();

        let curiosity = self.levels.curiosity_drive();
        let stress = self.levels.stress_index();
        let boredom = self.levels.boredom_index();

        // 1. High Curiosity Drive -> Proactive Exploration & Hypothesis Testing
        if curiosity > 0.55 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::ExploreKnowledgeGaps,
                urgency: curiosity,
                target_domain: "Synthesizer (0x0200)".to_string(),
                rationale: format!("Curiosity drive elevated ({:.1}%); exploring uncharted semantic constellation gaps", curiosity * 100.0),
            });
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::OptimizeAstHypotheses,
                urgency: curiosity * 0.9,
                target_domain: "Fabricator (0x0400)".to_string(),
                rationale: "Plasticity (ACh) optimal for AST hypothesis formulation and code optimization".to_string(),
            });
        }

        // 2. High Stress -> Memory Eviction & Self-Repair
        if stress > 0.40 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::ReapDormantMemory,
                urgency: stress,
                target_domain: "CompactionEngine (0x0100)".to_string(),
                rationale: format!("Stress index elevated ({:.1}%); triggering dormant specialist memory compaction", stress * 100.0),
            });
        }

        // 3. High Boredom -> Goal Discovery
        if boredom > 0.45 {
            impulses.push(AutonomicImpulse {
                kind: ImpulseKind::RebalanceFederationTokens,
                urgency: boredom,
                target_domain: "Orchestrator (0x0100)".to_string(),
                rationale: format!("Boredom index elevated ({:.1}%); rebalancing token metabolic allocations to stimulate tasks", boredom * 100.0),
            });
        }

        impulses.sort_by(|a, b| b.urgency.partial_cmp(&a.urgency).unwrap_or(std::cmp::Ordering::Equal));
        impulses
    }

    /// Dynamically allocates tokens across the 9 sovereign specialists based on active neurochemistry
    pub fn calculate_token_distribution(&self, total_pool: f32) -> Vec<SpecialistTokenAllocation> {
        let d = self.levels.dopamine;
        let s = self.levels.serotonin;
        let n = self.levels.noradrenaline;
        let a = self.levels.acetylcholine;

        // Dynamic weight factors based on neurochemical drives
        let weights = [
            ("Orchestrator", 0x0100, 1.0 + d * 0.5, "Strategic cortex driven by dopamine momentum"),
            ("Synthesizer", 0x0200, 1.0 + a * 0.8, "Semantic knowledge boosted by acetylcholine plasticity"),
            ("Presenter", 0x0300, 1.0 + s * 0.4, "Visual experience sustained by serotonin harmony"),
            ("Fabricator", 0x0400, 1.0 + d * 0.7, "Forge & engineering energized by reward prediction"),
            ("Sentinel", 0x0500, 1.0 + n * 0.9, "Auditor & safety heightened by noradrenaline vigilance"),
            ("Archivist", 0x0600, 1.0 + s * 0.5 + a * 0.3, "Memory chronicler consolidating balanced states"),
            ("Router", 0x0700, 1.0 + n * 0.4 + d * 0.3, "Router & mesh maintaining active throughput"),
            ("Aligner", 0x0800, 1.0 + s * 0.6, "Temporal resonance aligned with baseline harmony"),
            ("Perceiver", 0x0900, 1.0 + n * 0.8 + a * 0.4, "Sensory gating responsive to vigilance and focus"),
        ];

        let total_weight: f32 = weights.iter().map(|(_, _, w, _)| *w).sum();

        weights
            .iter()
            .map(|(name, opcode, w, reason)| {
                let share = *w / total_weight;
                SpecialistTokenAllocation {
                    specialist_name: name.to_string(),
                    domain_opcode: *opcode,
                    allocated_tokens: (total_pool * share).round(),
                    boost_reason: reason.to_string(),
                }
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_neurochemical_metrics() {
        let levels = NeurochemicalLevels::new(0.8, 0.4, 0.2, 0.9);
        assert!(levels.curiosity_drive() > 0.5);
        assert!(levels.stress_index() < 0.2);
        assert!(levels.metabolic_multiplier() > 1.0);
    }

    #[test]
    fn test_homeostasis_decay() {
        let mut engine = NeurochemicalHomeostasisEngine::new(NeurochemicalLevels::new(1.0, 1.0, 1.0, 1.0));
        engine.step_homeostasis(60.0); // 1 half-life
        assert!(engine.levels.dopamine < 1.0);
        assert!(engine.levels.dopamine > 0.5);
    }

    #[test]
    fn test_autonomic_impulses_and_token_distribution() {
        let engine = NeurochemicalHomeostasisEngine::new(NeurochemicalLevels::new(0.1, 0.2, 0.1, 0.9));
        let impulses = engine.evaluate_autonomic_impulses();
        assert!(!impulses.is_empty());
        assert_eq!(impulses[0].kind, ImpulseKind::ExploreKnowledgeGaps);

        let tokens = engine.calculate_token_distribution(900.0);
        assert_eq!(tokens.len(), 9);
        let total_allocated: f32 = tokens.iter().map(|t| t.allocated_tokens).sum();
        assert!((total_allocated - 900.0).abs() <= 5.0);
    }
}
