//! crates/adaptation_engine/src/mutation.rs
//! Code patch synthesis, diff generation, and AST-level transformations.

use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use tracing::info;

/// Proposed code patch generated by Adaptation Engine
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PatchProposal {
    pub target_file: String,
    pub original_checksum: String,
    pub patch_content: String,
    pub confidence_score: f32,
    pub mutation_type: String,
}

/// Software mutation and patch synthesis engine
pub struct CodeMutator;

impl CodeMutator {
    /// Synthesizes a pattern-substitution repair patch for a target source file (backwards-compatible)
    pub fn synthesize_repair(
        file_path: &str,
        source_code: &str,
        target_pattern: &str,
        replacement: &str,
    ) -> Result<PatchProposal> {
        info!(target: "chimera::mutation", %file_path, "Synthesizing pattern substitution patch proposal");

        let patched_content = source_code.replace(target_pattern, replacement);
        let modified = patched_content != source_code;
        let confidence = if modified { 0.95 } else { 0.0 };

        Ok(PatchProposal {
            target_file: file_path.to_string(),
            original_checksum: format!("{:016x}", fnv1a::compute(source_code.as_bytes())),
            patch_content: patched_content,
            confidence_score: confidence,
            mutation_type: "pattern_substitution".to_string(),
        })
    }

    /// Synthesizes a specific line-replacement patch
    pub fn synthesize_line_replacement(
        file_path: &str,
        source_code: &str,
        line_index_0_based: usize,
        new_line_content: &str,
    ) -> Result<PatchProposal> {
        let lines: Vec<&str> = source_code.lines().collect();
        if line_index_0_based >= lines.len() {
            bail!(
                "Line index {} out of bounds (file has {} lines)",
                line_index_0_based,
                lines.len()
            );
        }

        let mut output = Vec::with_capacity(lines.len());
        for (i, line) in lines.iter().enumerate() {
            if i == line_index_0_based {
                output.push(new_line_content);
            } else {
                output.push(line);
            }
        }

        let patched = output.join("\n");
        Ok(PatchProposal {
            target_file: file_path.to_string(),
            original_checksum: format!("{:016x}", fnv1a::compute(source_code.as_bytes())),
            patch_content: patched,
            confidence_score: 0.98,
            mutation_type: "line_replacement".to_string(),
        })
    }

    /// Synthesizes a block-wrapping patch (e.g. wrapping a risky call in a guard or condition)
    pub fn synthesize_wrap(
        file_path: &str,
        source_code: &str,
        target_pattern: &str,
        prefix: &str,
        suffix: &str,
    ) -> Result<PatchProposal> {
        let wrapped = format!("{}{}{}", prefix, target_pattern, suffix);
        Self::synthesize_repair(file_path, source_code, target_pattern, &wrapped)
    }

    /// Generates a simple unified diff string between original and patched contents
    pub fn generate_unified_diff(original: &str, modified: &str, file_name: &str) -> String {
        let orig_lines: Vec<&str> = original.lines().collect();
        let mod_lines: Vec<&str> = modified.lines().collect();

        let mut diff = format!("--- a/{}\n+++ b/{}\n", file_name, file_name);
        diff.push_str("@@ -1 +1 @@\n");

        for l in &orig_lines {
            if !mod_lines.contains(l) {
                diff.push_str(&format!("-{}\n", l));
            }
        }
        for l in &mod_lines {
            if !orig_lines.contains(l) {
                diff.push_str(&format!("+{}\n", l));
            }
        }
        diff
    }

    /// Validates and applies a patch proposal to the source code, checking original checksum integrity
    pub fn apply_patch(source_code: &str, patch: &PatchProposal) -> Result<String> {
        let current_checksum = format!("{:016x}", fnv1a::compute(source_code.as_bytes()));
        if current_checksum != patch.original_checksum {
            bail!(
                "Patch validation failed: source checksum {} does not match expected {}",
                current_checksum,
                patch.original_checksum
            );
        }
        Ok(patch.patch_content.clone())
    }
}

pub mod fnv1a {
    /// 64-bit Fowler–Noll–Vo 1a hash for deterministic, allocation-free checksums
    pub fn compute(bytes: &[u8]) -> u64 {
        let mut hash = 0xcbf29ce484222325u64;
        for &b in bytes {
            hash ^= b as u64;
            hash = hash.wrapping_mul(0x100000001b3);
        }
        hash
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_patch_synthesis() {
        let src = "fn run() { panic!(\"error\"); }";
        let patch = CodeMutator::synthesize_repair(
            "main.rs",
            src,
            "panic!(\"error\");",
            "eprintln!(\"graceful error\");",
        )
        .unwrap();

        assert_eq!(patch.confidence_score, 0.95);
        assert!(patch.patch_content.contains("graceful error"));

        let applied = CodeMutator::apply_patch(src, &patch).unwrap();
        assert_eq!(applied, patch.patch_content);
    }

    #[test]
    fn test_line_replacement_and_diff() {
        let src = "line 1\nline 2\nline 3";
        let patch = CodeMutator::synthesize_line_replacement("test.rs", src, 1, "line 2 modified").unwrap();
        assert_eq!(patch.patch_content, "line 1\nline 2 modified\nline 3");

        let diff = CodeMutator::generate_unified_diff(src, &patch.patch_content, "test.rs");
        assert!(diff.contains("-line 2"));
        assert!(diff.contains("+line 2 modified"));
    }

    #[test]
    fn test_wrap_patch() {
        let src = "let x = risky_call();";
        let patch = CodeMutator::synthesize_wrap(
            "mod.rs",
            src,
            "risky_call()",
            "if let Ok(val) = ",
            " { val } else { 0 }",
        )
        .unwrap();
        assert!(patch.patch_content.contains("if let Ok(val) = risky_call() { val } else { 0 }"));
    }
}
