[env]
CRATE_CC_NO_DEFAULTS = "1"
ZSTD_SYS_USE_PKG_CONFIG = "0"
ZSTD_SYS_STATIC = "1"
LIBCLANG_PATH = "C:\\Program Files\\LLVM\\lib"
BINDGEN_EXTRA_CLANG_ARGS = '-I"C:\\Program Files\\Microsoft Visual Studio\\18\\Insiders\\VC\\Tools\\MSVC\\14.51.36231\\include" -I"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\ucrt"'
PKG_CONFIG = "false"
ZSTD_SYS_PKG_CONFIG_NAME = "none"
ZSTD_LIB_DIR = "C:\\Program Files\\zstd\\lib"
ZSTD_INCLUDE_DIR = "C:\\Program Files\\zstd\\include"

