// Aaroneous Library Module
// Central operations for A-Run and Shared Memory Synapse

pub mod agents;
pub mod biology;
pub mod control;
pub mod constellation;
pub mod genetics;
pub mod self_digestion;
pub mod skill_system;
pub mod skill_fusion;
pub mod fusion_federation;
pub mod event_loop;
pub mod rank_evolution;
pub mod capability_dashboard;
pub mod crisis_coordinator;
pub mod data_ingestion;
pub mod content_analyzer;
pub mod capability_matcher;
pub mod data_distillation;
pub mod inbox_system;
pub mod ingestion_federation;
pub mod inbox_broadcaster;
pub mod nats_client;
pub mod persistence;
pub mod hive_runtime;
pub mod tracing_init;
pub mod config_validator;
pub mod tui_framework;
pub mod file_watcher;
pub mod cli;
pub mod integration_tests;
pub mod llm;
pub mod specialist_memory;
pub mod specialist_memory_reflection;
pub mod task_analysis;
pub mod capability_matching_v2;
pub mod autonomous_planning;
pub mod autonomous_coordinator;
pub mod error_recovery;
pub mod specialist_collaboration;
pub mod goal_driven_autonomy;
pub mod specialist_memory_compression;
pub mod specialist_memory_archival;
pub mod specialist_memory_caching;
pub mod specialist_memory_cached;
pub mod phase3_performance_benchmarks;
pub mod advanced_model_selection;
pub mod phase3_integration_summary;
pub mod enterprise_auth;
pub mod enterprise_rbac;
pub mod enterprise_monitoring;
pub mod enterprise_scaling;
pub mod advanced_intelligence;
// mcp_bridge (NATS-based) is removed — superseded by mcp_service (HTTP+SSE on port 8766).
// The mcp_bridge module used the deprecated nats::asynk API and was never connected
// to any production hive path. All MCP functionality is now in mcp_service/.
pub mod mcp_service;
pub mod event_log;
pub mod raft_consensus;
pub mod agentic_players;
pub mod wasm_ebus_bridge;
pub mod hid_driver;
pub mod federation;
#[cfg(test)]
mod integration_tests_phase2;
mod specialist_memory_tests;
pub mod shared_memory;

pub use agents::{Agent, AgentType, SpecialistAgent, RelicAgent, UserAgent, BaseAgent, CognitiveBias, Domain, create_specialist, create_relic};
pub use biology::{SystemBiology, SpecialistMetabolism, ThrottleState, SystemHealthReport, SpecialistHealth};
pub use control::{ControlPlane, ControlMessage, SpecialistState, parse_control_message};
pub use constellation::{Constellation, ConstellationNode, ConstellationQuery, NodeType, NodeStatus, Priority, SpatialCoord, ClusteringContext, RelationshipType};
pub use genetics::{SpecialistGenome, GeneticLocus, GeneticCategory, BreedingOperation, GeneticAnalyzer};
pub use self_digestion::{DigestionEngine, DigestionTask, SpecialistSoul, PersonalitySoul, RelationalSoul, NarrativeSoul, ExperienceSoul, DigestionConfig, DigestionEvent};
pub use skill_system::{Skill, SkillType, SkillOrigin, SoulRank, FusedSkill, SpecialistSkillSet, SkillRegistry};
pub use skill_fusion::{SkillFusionEngine, FusionRequest, FusionResult, FusionSuggestion, CompatibilityScore, CompatibilityMatrix};
pub use fusion_federation::{FusionEvent, FusionEventType, FusionCapability, FusionFederationBroadcaster, FusionQueryAPI, FusionMentorshipTransfer, MentorshipStatus};
pub use event_loop::{SkillEventLoop, SkillExecutionEvent, LevelUpEvent, AwakeningEvent, RankEvolutionEvent, XPCalculation, BreakthroughDetection, ExecutionResult, SkillStatistics};
pub use rank_evolution::{RankRequirements, RankMilestone, RankProgressionTracker, RankEvolutionCoordinator};
pub use capability_dashboard::{CapabilityDashboard, SpecialistStatus, SkillTreeNode, CapabilitySummary, CrisisCapability, DashboardQuery, HealthStatus};
pub use crisis_coordinator::{CrisisCoordinator, CrisisIncident, CrisisSeverity, CrisisStatus, CrisisResponseTeam, TeamStatus, CrisisMetrics, CrisisStatistics};
pub use data_ingestion::{DataSource, FileFormat, IngestibleData, IngestionStatus, DataMetadata, IngestionConfig, CopyResult, copy_file_non_destructive};
pub use content_analyzer::{ContentAnalyzer, ContentAnalysis, StructuralAnalysis};
pub use capability_matcher::{CapabilityMatcher, CapabilityMatch, SpecialistProfile, SkillTrainingExample};
pub use data_distillation::{DistillationEngine, DistillationConfig, DistillationResult, QualityAssessment, DataCrystallizer, CrystallizedData};
pub use inbox_system::{InboxSystem, InboxStats, ProcessingResult};
pub use ingestion_federation::{IngestionEvent, IngestionStatus as FedIngestionStatus, ClassificationResult, QualityMetric, SpecialistUpdate, IngestionStats as FedIngestionStats, FailureEvent, IngestionQuery, QueryResponse, FederationConfig, IngestionTopics};
pub use inbox_broadcaster::{InboxBroadcaster};
pub use nats_client::{NatsClient, NatsClientConfig, NatsPublisher, NatsSubscriber, NatsRequestReply, ConnectionStatus, NatsHealthStatus};
pub use persistence::{PersistenceManager, SpecialistRecord, SkillRecord, EventRecord, ConstellationRecord, IngestionRecord, HiveStatistics};
pub use hive_runtime::{HiveRuntime, HiveRuntimeConfig, RuntimeStatus, RuntimeStatistics};
pub use tracing_init::{init_tracing, init_tracing_with_file};
pub use config_validator::{ValidatedRuntimeConfig, ValidatedIngestionConfig};
pub use tui_framework::{TuiApp, TuiRunner, Page, TuiEvent};
pub use file_watcher::{FileWatcher, FileWatcherConfig, FileEvent};
pub use cli::{CliArgs, Commands, parse_args, execute};
pub use llm::{LLMClient, LLMConfig, ProviderType, LLMProvider, GGUFProvider, MockProvider, ModelRegistry, ModelInfo, ModelType, ModelLoader, TOP_RECOMMENDED_MODELS, ModelEnvironment, DetectedEnvironment, ModelEnvironmentDetector};
pub use llm::types::*;
pub use specialist_memory::{SpecialistMemory, MemoryEntry, MemoryType, Confidence, MemorySource, DecisionRecord, Strategy, Goal, GoalStatus, MemoryStats};
pub use specialist_memory_reflection::{MemoryReflectionEngine, ReflectionTrigger, ReflectionResult, DecisionPattern, LearningEvent};
pub use task_analysis::{TaskAnalysisEngine, Task, TaskPriority, TaskAnalysisResult, SpecialistRecommendation, TaskBatch, TaskBatchType};
pub use capability_matching_v2::{CapabilityMatchingEngine, SpecialistCapabilityMatch, ResourceAllocation, RiskLevel};
pub use autonomous_planning::{AutonomousPlanningEngine, AutonomousPlan, ExecutionStep, Contingency, ExecutionTracker, ExecutionStatus};
pub use autonomous_coordinator::{AutonomousCoordinator, TaskExecutionState, TaskCoordinationStatus, TaskSummary};
pub use error_recovery::{ErrorRecoveryEngine, ExecutionError, ErrorType, RecoveryStrategy, RecoveryAction, ActionType, FailureAnalysis};
pub use specialist_collaboration::{SpecialistCollaborationEngine, HelpRequest, HelpResponse, CollaborationRecord, CollaborationMetrics, Urgency, AssistanceType};
pub use goal_driven_autonomy::{GoalDrivenAutonomyEngine, AutonomousGoal, GoalCategory, GoalPriority, AutonomousGoalStatus, Milestone};
pub use specialist_memory_compression::{MemoryCompressor, CompressedMemoryEntry, CompressionStats, MemoryTier, MemoryTierManager};
pub use specialist_memory_archival::{MemoryArchiveManager, ArchivalConfig, ArchiveStats, CleanupPolicy, PolicyBasedCleanupManager};
pub use specialist_memory_caching::{CacheKey, CacheEntry, L1Cache, L2Cache, L3Cache, MultiLayerCache, MultiLayerCacheConfig, CacheStats, CacheInvalidationManager, InvalidationPattern, CacheMemoryUsage};
pub use specialist_memory_cached::{CachedSpecialistMemory, CacheMemoryUsageStats};
pub use phase3_performance_benchmarks::{Phase3Benchmarks, BenchmarkResult, OperationMetrics};
pub use advanced_model_selection::{TaskComplexity, TaskComplexityAnalyzer, ModelProfile, ModelProfileDatabase, ModelSelectionScore, ModelScorer, ModelSelector};
pub use phase3_integration_summary::{Phase3Summary, Phase3ComponentMetrics, CodeStats, PerformanceImprovements, Phase3Checklist};
pub use enterprise_auth::{Role, Permission, User, AuthToken, ApiKey, Tenant, SubscriptionTier, AuditLogEntry, AuditResult, AuthenticationManager, AuthorizationManager, ApiKeyManager, MultiTenantManager};
pub use enterprise_rbac::{CustomRole, ResourceAccess, ResourceType, AccessPolicy, PolicyRule, RBACManager};
pub use enterprise_monitoring::{SystemHealth, PerformanceMetrics, TenantMetrics, Alert, AlertComparison, MonitoringDashboard, DashboardReport};
pub use enterprise_monitoring::CacheStats as MonitoringCacheStats;
pub use enterprise_scaling::{ClusterNode, ClusterConfig, ClusterManager, ClusterStatus, LoadBalancingStrategy, LoadBalancer, ReplicaSet, ReplicationManager, BackupConfig, BackupManager, BackupMetadata, BackupStatus, SLAMetrics};
pub use enterprise_scaling::NodeStatus as ClusterNodeStatus;
pub use advanced_intelligence::{TimeSeriesPoint, MetricStatistics, AnomalyDetection, AnomalySeverity, AnomalyDetector, Forecast, ForecastTrend, Forecaster, ScalingDecision, ScalingAction, ScalingUrgency, AutoScaler, SelfHealingAction, HealingActionType, HealingSeverity, SelfHealingEngine, OptimizationRecommendation, OptimizationCategory, DifficultyLevel, OptimizationEngine};
pub use mcp_service::{McpService, ServiceConfig, Capability, CapabilityDomain, CapabilityResult, Transport, AuthProvider, ApiKeyAuth, OAuth2Auth, HttpServer};
pub use event_log::{EventLog, FederationEvent, EventType, Operation, EventLogStore, EventLogReplicator, EventLogStats, CompactionResult};
pub use raft_consensus::{RaftNode, RaftLog, RaftEngine, RaftState, RaftConfig, LogEntry, Term, LogIndex, NodeId, PersistentState, VolatileState, AppendEntriesRpc, RequestVoteRpc, Snapshot, ApplyCommand};
pub use agentic_players::{Observation, GameState, PlayerAction, InferredIntent, DecisionRule, PlayStyle, HumanizationPatterns, PlayerPolicy, EmulationStats, GameEpisode, Insight};
pub use wasm_ebus_bridge::{WasmEbusBridge, EbusEvent, EbusEventType, WasmMemory, WitInterface, ActionExecutor, RingBuffer};
pub use hid_driver::{HidDriver, HidCommand, HidResponse, MouseButton};
pub use shared_memory::SharedMemorySynapse;