// LLM Integration Types
// Core data structures for reasoning and analysis

use serde::{Deserialize, Serialize};

/// Context for analyzing a task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskAnalysisContext {
    pub task_id: String,
    pub file_name: String,
    pub file_size: u64,
    pub file_type: String,
    pub data_sample: String,           // First N rows/bytes
    pub specialist_skills: Vec<String>, // Current specialist skills
    pub specialist_domain: String,
    pub team_context: String, // What other specialists are available
}

/// Result of task analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskAnalysis {
    pub task_id: String,
    pub analysis_type: String, // e.g., "sentiment_analysis", "data_cleaning"
    pub complexity: Complexity,
    pub recommended_approach: String,
    pub estimated_time_minutes: u32,
    pub confidence_percentage: u32,
    pub suggested_collaborators: Vec<String>, // Names of specialists to ask
    pub potential_risks: Vec<String>,
    pub reasoning: String, // Why this approach
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum Complexity {
    Simple,    // <5 minutes
    Moderate,  // 5-30 minutes
    Complex,   // 30+ minutes
}

/// Context for finding collaborators
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecialistContext {
    pub name: String,
    pub archetype: String,
    pub rank: u32,
    pub xp: u32,
    pub skills: Vec<SkillInfo>,
    pub recent_lessons: Vec<String>,
    pub collaboration_history: Vec<String>,
    pub current_goal: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillInfo {
    pub name: String,
    pub level: u32,
    pub is_awakened: bool,
}

/// Suggestion for collaboration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollaboratorSuggestion {
    pub specialist_name: String,
    pub reason: String,
    pub relevance_score: f32, // 0.0-1.0
    pub complementary_skills: Vec<String>,
}

/// Execution plan generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub task_id: String,
    pub specialist_name: String,
    pub steps: Vec<PlanStep>,
    pub total_estimated_time: u32,
    pub success_probability: f32,
    pub reasoning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub sequence: u32,
    pub description: String,
    pub estimated_time_minutes: u32,
    pub required_skills: Vec<String>,
    pub checkpoints: Vec<String>, // Validation points
}

/// Context for failure analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FailureContext {
    pub task_id: String,
    pub specialist_name: String,
    pub error_message: String,
    pub attempted_approach: String,
    pub available_skills: Vec<String>,
    pub previous_attempts: Vec<String>,
}

/// Analysis of failure with recovery suggestion
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FailureAnalysis {
    pub root_cause: String,
    pub explanation: String,
    pub prevention_strategy: String,
    pub recovery_approach: String,
    pub new_strategy: String,
    pub confidence_percentage: u32,
}

/// Explanation of a skill
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillExplanation {
    pub skill_name: String,
    pub description: String,
    pub use_cases: Vec<String>,
    pub example: String,
    pub how_to_improve: String,
    pub synergies_with: Vec<String>, // Other skills it combines well with
}

/// Specialist's reasoning about a decision
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecisionReasoning {
    pub decision: String,
    pub reasoning: String,
    pub alternatives_considered: Vec<String>,
    pub confidence_level: f32, // 0.0-1.0
    pub reasoning_timestamp: String,
}

/// Goal suggestion for specialist
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalSuggestion {
    pub goal_description: String,
    pub rationale: String,
    pub target_skills: Vec<String>,
    pub estimated_timeframe_days: u32,
    pub milestones: Vec<String>,
    pub expected_impact: String,
}

/// Specialist's memory of a lesson
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LessonMemory {
    pub lesson_id: String,
    pub lesson_text: String,
    pub when_learned: String,
    pub context: String,
    pub applicability: f32, // 0.0-1.0
}

/// Specialist's strategy for task type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Strategy {
    pub strategy_id: String,
    pub task_type: String,
    pub approach: String,
    pub steps: Vec<String>,
    pub success_rate: f32, // Based on past experience
    pub last_used: String,
    pub improvements_noted: Vec<String>,
}

/// LLM Query for reasoning
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMQuery {
    pub query_type: QueryType,
    pub content: String,
    pub context: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum QueryType {
    TaskAnalysis,
    CollaboratorFinding,
    ExecutionPlanning,
    FailureAnalysis,
    SkillExplanation,
    StrategyDecision,
    GoalSetting,
}

/// LLM Response wrapper
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    pub response_type: ResponseType,
    pub content: String,
    pub tokens_used: u32,
    pub confidence: f32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ResponseType {
    Analysis,
    Plan,
    Suggestion,
    Explanation,
    Decision,
}

// ================================================================
// Federation Visionary types: UI/UX design generation
// ================================================================

/// Context for generating a UI/UX design variant.
/// Passed to `LLMProvider::generate_design()` by the Visionary specialist.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DesignContext {
    /// What kind of user intent to address (e.g., "dashboard", "onboarding flow")
    pub intent: String,
    /// Style preferences from engrams / previous user feedback
    pub style_hints: Vec<String>,
    /// Constraints (e.g., "mobile-first", "accessibility required", "dark theme")
    pub constraints: Vec<String>,
    /// Number of distinct variants to generate
    pub variants_requested: usize,
    /// Recent approved designs to learn from
    pub approved_examples: Vec<String>,
    /// Recent rejected designs to avoid
    pub rejected_examples: Vec<String>,
}

/// A single UI/UX design variant generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DesignVariant {
    /// Short title
    pub title: String,
    /// Prose description of the design (layout, colors, typography, interactions)
    pub description: String,
    /// Color palette tokens (hex strings or named tokens)
    pub colors: Vec<String>,
    /// Typography choices
    pub typography: String,
    /// Layout approach (e.g., "single-column", "card grid", "sidebar-nav")
    pub layout: String,
    /// How likely the model thinks this design will be approved (0.0-1.0)
    pub confidence: f32,
    /// Model's reasoning for this choice
    pub reasoning: String,
}

/// The full design generation response from the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DesignGeneration {
    /// Which intent this generation addresses
    pub intent: String,
    /// The generated variants (length <= `DesignContext::variants_requested`)
    pub variants: Vec<DesignVariant>,
    /// Estimated token cost (0 for local GGUF)
    pub tokens_used: u32,
    /// Overall confidence in the generation batch
    pub batch_confidence: f32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_task_analysis_context_creation() {
        let context = TaskAnalysisContext {
            task_id: "task1".to_string(),
            file_name: "data.csv".to_string(),
            file_size: 1024,
            file_type: "csv".to_string(),
            data_sample: "id,name,value\n1,A,100".to_string(),
            specialist_skills: vec!["RAG".to_string()],
            specialist_domain: "analysis".to_string(),
            team_context: "Team has 6 specialists".to_string(),
        };

        assert_eq!(context.task_id, "task1");
    }

    #[test]
    fn test_task_analysis_serialization() {
        let analysis = TaskAnalysis {
            task_id: "task1".to_string(),
            analysis_type: "data_analysis".to_string(),
            complexity: Complexity::Moderate,
            recommended_approach: "Use RAG".to_string(),
            estimated_time_minutes: 30,
            confidence_percentage: 85,
            suggested_collaborators: vec!["Circe".to_string()],
            potential_risks: vec!["Data quality".to_string()],
            reasoning: "Good approach".to_string(),
        };

        let json = serde_json::to_string(&analysis).unwrap();
        let deserialized: TaskAnalysis = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.task_id, "task1");
    }
}
